def COLOR_MAP = [
    SUCCESS: 'good', 
    FAILURE: 'danger',
]

pipeline {
    agent any
    tools {
        nodejs "nodejs"
        jdk "OracleJDK8"
    }
    
    environment {
        acrServer = 'carshowcaseimg.azurecr.io'
        acrCredential = 'acr-cred' // Jenkins credential ID for ACR
    }

    stages {
        stage('Build'){
            steps {
                // sh 'npm install'
                echo "Build"
            }
        }

        stage('Test'){
            steps {
               // sh 'mvn test'
               echo "Test"
            }
        }

        stage('Build App Image') {
            steps {
                sh 'docker image build -t carprofileregistry.azurecr.io/mycarimage:${BUILD_NUMBER} .'
            }
        }
            
        stage('Upload App Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'acr_cred', passwordVariable: 'password', usernameVariable: 'username')]) {
                    sh 'docker login -u ${username} -p ${password} carprofileregistry.azurecr.io'
                    sh "docker image push carprofileregistry.azurecr.io/mycarimage:${BUILD_NUMBER}"
                }
            }
        }
    }
  
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#vprofilecicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
